# fly.toml app configuration file generated for llm-test-123 on 2023-08-01T18:48:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "llm-test-123"
primary_region = "dfw"

[build]
  builder = "paketobuildpacks/builder:full"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
